name: ci unit test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pipenv
        run: pip install --user pipenv

      - name: install pytest
        run: pip install pytest

      - name: install dependencies
        run: pipenv install --dev

      - name: run unit test [pytest]
        run: pipenv run pytest blackjack_test.py

